# Generated by Django 5.2.6 on 2025-12-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_sales_point_book_idx_book_sales_point'),
        ('books', '0005_remove_book_sales_point'),
    ]

    operations = [
    ]
