# Generated by Django 5.2.6 on 2025-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_merge_20251224_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sales_point',
            field=models.IntegerField(default=0, help_text='알라딘 API salesPoint 값 (누적 판매/인기 지표)', verbose_name='알라딘 판매 지수'),
        ),
    ]
